# Generated by Django 3.0.3 on 2020-02-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200219_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterModelOptions(
            name='polling',
            options={'verbose_name': 'Опросник', 'verbose_name_plural': 'Опросники'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=250, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один ответ'), ('multiple', 'Несколько ответов')], default='single', max_length=20, verbose_name='Тип вопроса'),
        ),
    ]
