# Generated by Django 3.0.3 on 2020-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200219_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
    ]
