# Generated by Django 3.0.3 on 2020-02-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200219_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='poll_duration',
            field=models.DurationField(help_text='формат `[ДД] [[чч:]мм:]сс`', null=True, verbose_name='Время на опрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_duration',
            field=models.DurationField(help_text='формат `[ДД] [[чч:]мм:]сс`', null=True, verbose_name='Время на вопрос'),
        ),
    ]
