# Generated by Django 3.0.3 on 2020-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200219_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='questions',
            field=models.ManyToManyField(related_name='polling', to='polls.Question'),
        ),
    ]
