# Generated by Django 3.0.3 on 2020-02-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200219_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polling',
            old_name='poll_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='polling',
            old_name='poll_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_duration',
            new_name='duration',
        ),
    ]
