# Generated by Django 3.0.3 on 2020-02-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200219_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='polling',
            name='selected_choices',
            field=models.ManyToManyField(related_name='selected_choice', to='polls.Choice'),
        ),
    ]
