# Generated by Django 3.0.3 on 2020-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_polling_selected_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='selected_choices',
            field=models.ManyToManyField(related_name='polling', to='polls.Choice'),
        ),
    ]
