# Generated by Django 3.0.3 on 2020-02-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200227_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='questions',
            field=models.ManyToManyField(related_name='polling_questions', to='polls.Question'),
        ),
        migrations.AlterField(
            model_name='polling',
            name='selected_choices',
            field=models.ManyToManyField(related_name='polling_choices', to='polls.Choice'),
        ),
    ]
