# Generated by Django 3.0.3 on 2020-03-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200227_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polling',
            name='selected_choices',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='polls.Polling')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='polls.Choice')),
            ],
        ),
    ]
