# Generated by Django 3.0.3 on 2020-03-05 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0015_auto_20200301_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='q_type',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='polling',
            name='owners',
            field=models.ManyToManyField(related_name='polling_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='polling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='polls.Polling'),
        ),
    ]
