# Generated by Django 3.0.3 on 2020-03-06 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20200306_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='selected',
            new_name='result',
        ),
    ]
