# Generated by Django 3.0.3 on 2020-03-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20200306_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='result',
        ),
        migrations.AddField(
            model_name='result',
            name='selected_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
            preserve_default=False,
        ),
    ]
