# Generated by Django 3.0.3 on 2020-12-14 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0023_auto_20200306_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='owners',
            field=models.ManyToManyField(related_name='pollings', to=settings.AUTH_USER_MODEL),
        ),
    ]
